In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('play_tennis.csv')

In [6]:
df.drop(columns=['day'], inplace=True)

In [9]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [13]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [15]:
# probability of Yes
py=9/14

#probability of No
pn=5/14


print("Probafbility of Yes: ",py)
print("Probability of No: ",pn)

Probafbility of Yes:  0.6428571428571429
Probability of No:  0.35714285714285715

In [16]:
#Outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [17]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [18]:
#Temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [19]:
Pcn=1/5
Phn=2/5
Pmn=2/5

Pcy=3/9
Phy=2/9
Pmy=4/9

In [20]:
#Humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [24]:
Phighn=4/5
Pnormaln=1/5

Phighy=3/9
Pnormaly=6/9

In [22]:
#Wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [23]:
Psn=3/5
Pwn=2/5

Psy=3/9
Pwy=6/9

In [28]:
#Outlook=Sunny,temp=Hot,Humidity=High, wind=Week

Pyes=py*Psy*Phy*Phighy*Pwy

In [29]:
Pyes

0.015873015873015872

In [32]:
Pno=pn*Psn*Phn*Phighn*Pwn

In [33]:
print(Pno)

0.05485714285714286

In [34]:
#Prediction No play

In [35]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
      % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 75 points : 4