In [2]:
import torch
import torch.nn as nn

In [7]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [8]:
features=torch.rand(10,5)
model=Model(features.shape[1])

model(features)

tensor([[0.6000],
        [0.6145],
        [0.6639],
        [0.5775],
        [0.6907],
        [0.5400],
        [0.5769],
        [0.6883],
        [0.5112],
        [0.6225]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.weight

Parameter containing:
tensor([[ 0.3573, -0.3597, -0.1721,  0.4086,  0.2664]], requires_grad=True)

In [10]:
model.linear.bias

Parameter containing:
tensor([0.2656], requires_grad=True)

In [11]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [12]:
from torchinfo import summary

summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [19]:
class Model2(nn.Module):

 class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


  def forward(self,features):

    out=self.network(features)

    return out

In [21]:
features=torch.rand(10,5)
model=Model(features.shape[1])

model(features)

tensor([[0.5100],
        [0.5416],
        [0.4642],
        [0.4719],
        [0.4999],
        [0.4392],
        [0.5410],
        [0.5377],
        [0.3874],
        [0.4894]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear.weight

Parameter containing:
tensor([[ 0.1556,  0.3330, -0.2790,  0.0048, -0.3668]], requires_grad=True)

In [25]:
##Training Pipeline Using NN Module

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [28]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [29]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [30]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [31]:
X_train

array([[ 2.21423344,  0.56651298,  2.24808905, ...,  1.87933585,
        -0.26543868,  0.10162918],
       [ 0.56105367,  0.56195632,  0.59503597, ..., -0.20239113,
        -0.27353729, -0.23971396],
       [ 3.13713901,  1.25229028,  3.25990744, ...,  2.53316345,
        -0.89065152,  1.16578431],
       ...,
       [-0.56598367, -1.01692628, -0.62122803, ..., -1.05567374,
        -0.9829757 , -1.32750477],
       [-0.12609409, -0.72985672, -0.19526498, ..., -0.94099087,
        -0.87931347, -0.70143416],
       [-0.39347795, -0.73897004, -0.41761519, ..., -0.51532655,
         0.63512697, -0.30512433]])

In [32]:
y_train

369    M
329    M
82     M
70     M
480    B
      ..
338    B
358    B
404    B
357    B
403    B
Name: diagnosis, Length: 455, dtype: object

In [34]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [35]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [62]:
class MyModel(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [63]:
loss_function=nn.BCELoss()

In [64]:
learning_rate = 0.1
epochs = 25

In [65]:
# Ensure tensors are float32 (fixes dtype mismatch error)
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float().unsqueeze(1) # Reshape y_train_tensor here

# create model
model = MyModel(X_train_tensor.shape[1])

optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()



  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5996712446212769
Epoch: 2, Loss: 0.47936657071113586
Epoch: 3, Loss: 0.4108978807926178
Epoch: 4, Loss: 0.36591801047325134
Epoch: 5, Loss: 0.3335641622543335
Epoch: 6, Loss: 0.3088892102241516
Epoch: 7, Loss: 0.2892902195453644
Epoch: 8, Loss: 0.27325084805488586
Epoch: 9, Loss: 0.2598201632499695
Epoch: 10, Loss: 0.2483680099248886
Epoch: 11, Loss: 0.2384583204984665
Epoch: 12, Loss: 0.229778453707695
Epoch: 13, Loss: 0.22209782898426056
Epoch: 14, Loss: 0.2152421772480011
Epoch: 15, Loss: 0.2090768665075302
Epoch: 16, Loss: 0.20349615812301636
Epoch: 17, Loss: 0.1984156221151352
Epoch: 18, Loss: 0.19376689195632935
Epoch: 19, Loss: 0.18949393928050995
Epoch: 20, Loss: 0.18555039167404175
Epoch: 21, Loss: 0.18189740180969238
Epoch: 22, Loss: 0.1785021871328354
Epoch: 23, Loss: 0.17533688247203827
Epoch: 24, Loss: 0.17237761616706848
Epoch: 25, Loss: 0.16960375010967255

In [66]:
# model evaluation
with torch.no_grad():
  X_test_tensor = X_test_tensor.float()
  y_test_tensor = y_test_tensor.float().unsqueeze(1)
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6440443396568298